[general]
provider = gitcode

[gitee]
gitee-url = https://gitee.com
# get new token here https://gitee.com/profile/personal_access_tokens/new
token = <token>
members = members.txt

[gitcode]
gitcode-url = https://gitcode.com
# get new token from your GitCode account settings
token = <token>
members = members.txt
